apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: kadto-prod
spec:
  provider:
    gcpsm:
      projectID: "<gcp-project-id>"
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: kadto
            namespace: kadto-prod
