apiVersion: v1
kind: Service
metadata:
  name: kadto-api
  labels:
    app.kubernetes.io/name: kadto-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kadto
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kadto-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
